artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/logistic_mlruns/503018229812822053
creation_time: 1720871360337
experiment_id: '503018229812822053'
last_update_time: 1720871360337
lifecycle_stage: active
name: logistic_exp
