artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/xgb_mlruns/168540771648230627
creation_time: 1720871697437
experiment_id: '168540771648230627'
last_update_time: 1720871697437
lifecycle_stage: active
name: xgb_exp
