artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/random_forest_mlruns/814537078946993192
creation_time: 1720871655902
experiment_id: '814537078946993192'
last_update_time: 1720871655902
lifecycle_stage: active
name: randomforest_exp
