artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/logistic_mlruns/0
creation_time: 1720871359917
experiment_id: '0'
last_update_time: 1720871359917
lifecycle_stage: active
name: Default
