artifact_location: file:C:/Users/odhia/OneDrive/Desktop/datascienceproject/notebooks/Decision_tree_mlruns/975400655810343931
creation_time: 1720871467214
experiment_id: '975400655810343931'
last_update_time: 1720871467214
lifecycle_stage: active
name: tree_exp
